FROM build-$BUILD_TYPE as scalyr-testing
MAINTAINER Scalyr Inc <support@scalyr.com>
# Since test version of the image uses coverage, add command that runs the Agent with enabled coverage.
CMD ["coverage", "run", "--branch", "/usr/share/scalyr-agent-2/py/scalyr_agent/agent_main.py", "--no-fork", "--no-change-user", "start"]
